<?php

namespace App\Ollama\Tools;

use Cloudstudio\Ollama\Contracts\Tool;
use Illuminate\Support\Facades\DB;

class DatabaseQueryTool implements Tool
{
    /**
     * The name of the function that the LLM will see and call.
     */
    public function name(): string
    {
        return 'database_query';
    }

    /**
     * A description of the function, which guides the LLM on when to use it.
     */
    public function description(): string
    {
        return 'Queries the application database using an SQL SELECT statement to retrieve information about students, courses, or grades. Always return the SQL query and its results.';
    }

    /**
     * The parameters the LLM should pass to the function.
     */
    public function parameters(): array
    {
        return [
            'type' => 'object',
            'properties' => [
                'sql_query' => [
                    'type' => 'string',
                    'description' => 'The complete SQL SELECT query needed to answer the user request. MUST be a SELECT statement.',
                ],
            ],
            'required' => ['sql_query'],
        ];
    }

    /**
     * The function logic that executes the tool.
     * @param string $sql_query The SQL query generated by the LLM.
     * @return string The results of the query formatted as JSON.
     */
    public function handle(string $sql_query): string
    {
        try {
            
            $results = DB::select($sql_query);
            
            return json_encode($results);
            
        } catch (\Exception $e) {
            return 'Database Error: ' . $e->getMessage();
        }
    }
}